trigger:
- main 

pool:
  name: 'SH'  

variables:
  azureSubscription: 'Azure subscription 1'  
  resourceGroup: 'MyResourceGroup' 
  aksClusterName: 'MyK8sCluster'  
  nodeCount: 2  

steps:
- task: AzureCLI@2  
  inputs:
    azureSubscription: $(azureSubscription)  
    scriptType: 'bash'  
    scriptLocation: 'inlineScript'  
    inlineScript: |
      az aks create \
        --resource-group $(resourceGroup) \
        --name $(aksClusterName) \
        --node-count $(nodeCount) \
        --generate-ssh-keys  